import product1 from "../assets/product.jfif";
import product2 from "../assets/product1.jfif";
import product3 from "../assets/product2.jfif";
const productData = [
  {
    id: 1,
    name: 'Apple MacBook Pro 17"',
    color: "Silver",
    category: "Laptop",
    price: "$2999",
    description: "High-performance laptop for professionals",
    imageUrl: product1,
    inStock: true,
    rating: 4.5,
  },
  {
    id: 2,
    name: "Dell XPS 15",
    color: "Space Gray",
    category: "Laptop",
    price: "$2499",
    description: "Sleek and powerful laptop for creators",
    imageUrl: product2,
    inStock: false,
    rating: 4.7,
  },
  {
    id: 3,
    name: "HP Spectre x360",
    color: "Rose Gold",
    category: "Laptop",
    price: "$1999",
    description: "Convertible laptop with stunning design",
    imageUrl: product3,
    inStock: true,
    rating: 4.3,
  },
  {
    id: 4,
    name: "Lenovo ThinkPad X1 Carbon",
    color: "Black",
    category: "Laptop",
    price: "$1799",
    description: "Ultra-lightweight business laptop",
    imageUrl: product1,
    inStock: true,
    rating: 4.6,
  },
  {
    id: 5,
    name: "Apple iPhone 13 Pro",
    color: "Graphite",
    category: "Smartphone",
    price: "$999",
    description: "Flagship smartphone with Pro camera system",
    imageUrl: product3,
    inStock: true,
    rating: 4.8,
  },
  {
    id: 6,
    name: "Samsung Galaxy Watch 4",
    color: "Black",
    category: "Wearable",
    price: "$349",
    description: "Stylish smartwatch with health monitoring features",
    imageUrl: product2,
    inStock: false,
    rating: 4.4,
  },
  {
    id: 7,
    name: "Sony WH-1000XM4",
    color: "Black",
    category: "Headphones",
    price: "$349",
    description: "Premium noise-canceling headphones",
    imageUrl: product1,
    inStock: true,
    rating: 4.7,
  },
  {
    id: 8,
    name: "Microsoft Surface Laptop 4",
    color: "Platinum",
    category: "Laptop",
    price: "$1299",
    description: "Thin and light laptop with touchscreen display",
    imageUrl: product3,
    inStock: true,
    rating: 4.5,
  },
  {
    id: 9,
    name: "Google Pixel 6 Pro",
    color: "Stormy Black",
    category: "Smartphone",
    price: "$899",
    description: "Powerful flagship smartphone with advanced camera features",
    imageUrl: product3,
    inStock: true,
    rating: 4.6,
  },
  {
    id: 10,
    name: "LG UltraGear 27GN950-B",
    color: "Black",
    category: "Monitor",
    price: "$999",
    description: "27-inch 4K gaming monitor with IPS Nano display",
    imageUrl: product2,
    inStock: true,
    rating: 4.8,
  },
  {
    id: 11,
    name: "Bose QuietComfort Earbuds",
    color: "Triple Black",
    category: "Earbuds",
    price: "$279",
    description: "Wireless noise-canceling earbuds",
    imageUrl: product3,
    inStock: true,
    rating: 4.6,
  },
  {
    id: 12,
    name: "Amazon Kindle Oasis",
    color: "Graphite",
    category: "E-Reader",
    price: "$279",
    description: "High-resolution e-reader with adjustable warm light",
    imageUrl: product2,
    inStock: true,
    rating: 4.7,
  },
  {
    id: 13,
    name: "GoPro Hero 10 Black",
    color: "Black",
    category: "Action Camera",
    price: "$499",
    description: "4K action camera with advanced stabilization",
    imageUrl: product1,
    inStock: true,
    rating: 4.8,
  },
];

export default productData;
